Fix changing TFA method to SMS
Clicking the button "Change TFA method to SMS and send mail" on
Setup->Access->Staff->Show->Action would result in a stack trace:

  TypeError: Gems\User\DbUserDefinitionAbstract::setTwoFactorKey():
  Argument #2 ($newKey) must be of type string, null given, called in
  /app/vendor/gemstracker/gemstracker/src/User/User.php on line 123

Since we do this on purpose (see clearTwoFactorKey()), allow $newKey to
be null.